// Ink & Garden content-collection Vite plugin (ARCHITECTURE-SPINE AD-1..AD-4).
// Owns, in one build-time pass: glob `content/p/**/*.{md,mdx}` from disk →
// gray-matter parse → validate → draft-exclude → emit typed `content-index`
// via the virtual module `virtual:content-index`. Essay bodies are compiled by
// the `@mdx-js/rollup` `mdx()` plugin and pulled here through `import.meta.glob`
// (eager) — that is the AC6 "import.meta.glob (eager)" the plugin orchestrates.
// No runtime fetch (AD-3). Fails closed in build; warns in dev.

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import type { Plugin, ViteDevServer } from 'vite';
import type { PostMeta } from './schema';
import { validatePost } from './validate';

const VIRTUAL_ID = 'virtual:content-index';
const RESOLVED_ID = '\0virtual:content-index';
const CONTENT_DIR = 'content/p';

interface BuiltPost {
  meta: PostMeta;
  /** Absolute-to-root posix path used as the import.meta.glob key, e.g. `/content/p/hello-ink-garden.mdx`. */
  bodyPath?: string;
}

interface Collection {
  posts: BuiltPost[]; // reverse-chron, slug-ASC tiebreak — published only
}

let cache: Collection | null = null;
let projectRoot = process.cwd();

/** Build the published post collection. Throws on invalid content (fail-closed). */
export function buildCollection(root: string): Collection {
  const dir = path.resolve(root, CONTENT_DIR);
  if (!fs.existsSync(dir)) {
    // No collection → empty index. (Migration is a later story; v1 ships samples.)
    return { posts: [] };
  }

  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && /\.(md|mdx)$/.test(e.name))
    .sort((a, b) => a.name.localeCompare(b.name));

  const built: BuiltPost[] = [];

  for (const ent of entries) {
    const abs = path.join(dir, ent.name);
    const rel = `${CONTENT_DIR}/${ent.name}`; // for error messages
    const slug = ent.name.replace(/\.(md|mdx)$/, '');
    const raw = fs.readFileSync(abs, 'utf8');
    let parsed: ReturnType<typeof matter>;
    try {
      parsed = matter(raw);
    } catch (err) {
      throw new Error(
        `Content gate: ${rel} — frontmatter parse failed: ${String((err as Error).message)}`,
      );
    }

    const hasBody = parsed.content.trim().length > 0;

    // AC5: drafts are excluded from the index AND must not ship in the bundle.
    // Skip full validation for drafts (WIP content need not satisfy the published
    // gates); just record `.mdx` drafts so the eager body glob excludes them.
    if (parsed.data?.status === 'draft') {
      continue;
    }

    const { meta, isDraft } = validatePost(parsed.data, {
      slug,
      file: rel,
      hasBody,
    });

    // Defensive: validatePost may also flag a draft — keep it out of the index.
    if (isDraft) continue;

    let bodyPath: string | undefined;
    if (meta.type === 'essay') {
      if (!/\.mdx$/.test(ent.name)) {
        throw new Error(
          `Content gate: ${rel} — essay posts must be .mdx so the body compiles`,
        );
      }
      bodyPath = '/content/p/' + slug + '.mdx';
    }

    built.push({ meta, bodyPath });
  }

  // Reverse-chronological by date DESC; slug ASC tiebreak (FR-5 feed order).
  built.sort((a, b) => {
    if (a.meta.date !== b.meta.date) return b.meta.date.localeCompare(a.meta.date);
    return a.meta.slug.localeCompare(b.meta.slug);
  });

  return { posts: built };
}

/** Serialize the collection as the virtual module source. */
function emitVirtualModule(collection: Collection): string {
  const essayPaths = collection.posts
    .filter((p) => p.bodyPath)
    .map((p) => p.bodyPath as string);

  const lines: string[] = [
    '// AUTO-GENERATED by ink-garden-content (src/content/plugin.ts). Do not edit.',
    '',
  ];

  if (essayPaths.length === 0) {
    // No published essays — no MDX to compile. Keep the binding for consumers.
    lines.push('const essayBodies = {} as Record<string, unknown>;');
  } else {
    lines.push('const essayBodies = import.meta.glob(');
    lines.push(`  ${JSON.stringify(essayPaths)},`);
    lines.push('  { eager: true, import: "default" },');
    lines.push(');');
  }

  lines.push('');
  lines.push('export const posts = [');

  for (const { meta, bodyPath } of collection.posts) {
    const obj = serializePost(meta, bodyPath);
    lines.push(`  ${obj},`);
  }

  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

/** Serialize one Post as a JS object literal (string-safe). */
function serializePost(meta: PostMeta, bodyPath?: string): string {
  const fields: string[] = [];
  fields.push(`slug: ${JSON.stringify(meta.slug)}`);
  fields.push(`title: ${JSON.stringify(meta.title)}`);
  fields.push(`date: ${JSON.stringify(meta.date)}`);
  fields.push(`type: ${JSON.stringify(meta.type)}`);
  fields.push(`status: ${JSON.stringify(meta.status)}`);
  fields.push(`access: ${JSON.stringify(meta.access)}`);
  if (meta.excerpt !== undefined)
    fields.push(`excerpt: ${JSON.stringify(meta.excerpt)}`);
  if (meta.tags !== undefined) fields.push(`tags: ${JSON.stringify(meta.tags)}`);
  if (meta.ogImage !== undefined)
    fields.push(`ogImage: ${JSON.stringify(meta.ogImage)}`);

  if (meta.type === 'essay') {
    const key = JSON.stringify(bodyPath);
    fields.push(
      `body: () => Promise.resolve({ default: essayBodies[${key}] })`,
    );
  } else {
    fields.push(`strip: ${JSON.stringify(meta.strip)}`);
    if (meta.caption !== undefined)
      fields.push(`caption: ${JSON.stringify(meta.caption)}`);
    if (meta.notes !== undefined)
      fields.push(`notes: ${JSON.stringify(meta.notes)}`);
  }

  return `{ ${fields.join(', ')} }`;
}

/** The Ink & Garden content-collection Vite plugin. */
export function contentPlugin(): Plugin {
  return {
    name: 'ink-garden-content',
    enforce: 'pre',

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
      return null;
    },

    configResolved(config) {
      projectRoot = config.root;
    },

    load(id) {
      if (id !== RESOLVED_ID) return null;
      const collection = cache ?? buildCollection(projectRoot);
      cache = collection;
      return emitVirtualModule(collection);
    },

    buildStart() {
      // Validate + index up front so invalid content fails the build fast
      // (fail-closed, same discipline as the 1.1 contrast gate).
      cache = buildCollection(projectRoot);
    },

    configureServer(server: ViteDevServer) {
      // Surface validation errors in dev without crashing the server.
      try {
        cache = buildCollection(server.config.root);
      } catch (err) {
        server.config.logger.warn(`  \u26a0 ${String((err as Error).message)}\n`);
      }
    },
  };
}